apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nodeapp-project
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 2 
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp-k8s
          image: hannidocker/nodeapp:1.10 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000 


---

apiVersion: v1 
kind: Service 
metadata: 
  name: nodeapp-project-svc
spec:
  selector:
    app: nodeapp
  ports:
    - protocol: "TCP"
      port: 8080 
      targetPort: 3000 #
  type: NodePort 
